// GameEnum.h
#ifndef GAMEENUM_H
#define GAMEENUM_H

enum ObjType 
{
	GO_BOARD,
	GO_LOCKED_TILE,
	GO_PIECE,
};

enum GameObjectID
{
	GAMEOBJECTID_NONE
};

//XENUM(RenderSortLayer)
//{
//	SORTLAYER_BY_MATERIAL = RENDER_SORT_BY_MATERIAL,
//
//	SORTLAYER_WORLD = SORTLAYER_DEFAULT_OPAQUE,
//	SORTLAYER_SKYBOX,
//	SORTLAYER_TRANSPARENT = SORTLAYER_DEFAULT_TRANSPARENT,
//	//SORTLAYER_UI,
//	SORTLAYER_PARTICULATES,
//	SORTLAYER_RETICLE,
//	SORTLAYER_DEBUG,
//};

#endif // GAMEENUM_H
